# Generated by Django 5.2.1 on 2025-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='state',
            field=models.CharField(choices=[('PU', 'PUBLICADO'), ('BR', 'BORRADOR'), ('PR', 'PRIVADO')], default='BR', max_length=2),
        ),
    ]
